format = "$username$directory[(\\($git_branch$git_commit( $git_status)\\))](fg:cyan)\n$character"

[character]
success_symbol = "[\\$](green)"
error_symbol = "[\\$](red)"

[directory]
truncate_to_repo = false
format = "[$path]($style) [$read_only]($read_only_style)"
style = "none"
read_only = " "

[git_branch] 
format = "[$branch]($style)"
style = "fg:cyan"

[git_commit]
format = "($hash$tag)"
tag_symbol = ""
tag_disabled = false

[git_status]
format = "[$all_status$ahead_behind](bold fg:cyan)"
deleted = "D"
modified = "M"
renamed = "R"
untracked = "U"
