[font]
size = 11

[font.normal]
family = "monospace"

[keyboard]
bindings = [
    { action = "SpawnNewInstance",  key = "Return", mods = "Shift|Super" },
    { action = "Last", key = 5, mode = "Vi|~Search", mods = "Shift" },
    { action = "First", key = 7, mode = "Vi|~Search", mods = "Shift" },
    { chars = "\u001B[15;4~", key = "F5", mods = "Shift" },
    { chars = "\u001B[15;6;5~", key = "F5", mods = "Control|Shift" },
    # { chars = "source ~/scripts/open-project.fish\n", key = "F", mods = "Control" }
]

[window]
dynamic_padding = true

[shell]
program = "/bin/fish"

# [window.padding]
# y = 5

# Nord
[colors.bright]
black = "#4c566a"
blue = "#81a1c1"
cyan = "#8fbcbb"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#eceff4"
yellow = "#ebcb8b"

[colors.cursor]
cursor = "#d8dee9"
text = "#2e3440"

[colors.dim]
black = "#373e4d"
blue = "#68809a"
cyan = "#6d96a5"
green = "#809575"
magenta = "#8c738c"
red = "#94545d"
white = "#aeb3bb"
yellow = "#b29e75"

[colors.normal]
black = "#1E2127"
blue = "#81a1c1"
cyan = "#88c0d0"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#e5e9f0"
yellow = "#ebcb8b"

[colors.primary]
background = "#1E2127"
dim_foreground = "#a5abb6"
foreground = "#d8dee9"

# [colors.search.footer_bar]
# background = "#434c5e"
# foreground = "#d8dee9"

[colors.search.matches]
background = "#88c0d0"
foreground = "CellBackground"

[colors.selection]
background = "#4c566a"
text = "CellForeground"

[colors.vi_mode_cursor]
cursor = "#d8dee9"
text = "#2e3440"

# Github light
# [colors.primary]
# background = "0xffffff"
# foreground = "0x1F2328"
#
# [colors.cursor]
# text = "0xffffff"
# cursor = "0x1f2328"
#
# [colors.normal]
# black = "0x24292f"
# red = "0xcf222e"
# green = "0x116329"
# yellow = "0x4d2d00"
# blue = "0x0969da"
# magenta = "0x8250df"
# cyan = "0x1b7c83"
# white = "0x6e7781"
#
# [colors.bright]
# black = "0x57606a"
# red = "0xa40e26"
# green = "0x1a7f37"
# yellow = "0x633c01"
# blue = "0x218bff"
# magenta = "0x8250df"
# cyan = "0x1b7c83"
# white = "0x6e7781"
